-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgfcOgTRGfjMyFhlj0
GIKtnKaC2IifQXhNWmWd1Cnt0VqgCgYIKoZIzj0DAQehRANCAATMg6IKfqkHWS8e
i7OIuvf4p3xxkfskggYpYKetPKNo4yjaacMV+an9X8aNSrCAGF8dqsZ4km2Mi4tG
WrWSdLFL
-----END PRIVATE KEY-----